<h1 style="text-align: center;"><strong>1. Solución de Sistemas de Ecuaciones Métodos Directos</strong></h1>

<a id='biseccion'></a>
<h2><span style="color: #993300;"><span style="text-decoration: underline;"><strong>M&eacute;todo 1:</strong> Eliminación Gaussiana</span></span></h2>

<h3><strong>a) Formulaci&oacute;n Matem&aacute;tica</strong></h3>


$Ax=b$

$x_{i}=\frac{1}{a_{ii}}\left ( b_{i} - \sum_{j=i+1}^{n} a_{ij} x_{j} \right ) $





<h3><strong>b) Valores Iniciales</strong></h3>

  <li>Matriz A de tamaño mxn</li>
  <li>Vector x de tamaño n</li>
  <li>Vector b de tamaño m</li>

<h3><strong>c) Ventajas y Desvantajas</strong></h3>

<div class="alert alert-block alert-success row">
    <div class="column">
        <p>
            <span style="text-decoration: underline;">
                <span style="text-decoration: underline;">
                    <strong>Ventajas:</strong>
                </span>
            </span>
        </p>
        <li>Siempre converge</li>
        <li>Útil como aproximación inicial de otros métodos</li>
    </div>
    <div class ="column">
        <p>
            <span style="text-decoration: underline;">
                <span style="text-decoration: underline;">
                    <strong>Desventajas:</strong>
                </span>
            </span>
        </p>
        <li>División entre cero.</li>
        <li>. La obtención de la solución depende de la condición del sistema. En sentido matemático, los sistemas bien condicionados son aquellos en los que un cambio en uno o más coeficientes provoca un cambio similar en la solución. Los sistemas mal condicionados son aquellos en los que cambios pequeños en los coeficientes provocan cambios grandes en la solución</li>
    </div>
</div>

<h3><strong>c) Pasos del m&eacute;todo (Pseudoc&oacute;digo)</strong></h3>

![](eliminacionGaussiana.PNG)

<h3><strong>d) C&oacute;digo en GNU Octave</strong></h3>

In [8]:
function X = gaussianElimination(A, B)
  n = length(A);
  X = [A, B];
  % For each row of augmented matrix
  for i=1:n
    pivot = X(i, i);
    pivotRow = X(i, :);
    % Multipliers' vector
    M = zeros(1, n - i);
    m = length(M);
    % Get each row multiplier
    for k=1:m
      M(k) = X(i + k, i) / pivot;
    endfor
    % Modify each row
    for k=1:m
      X(i + k, :) = X(i + k, :) - pivotRow*M(k);
    endfor
  endfor
  X = backSubstitution(X(1:n, 1:n), X(:,n+1));
endfunction


function X = backSubstitution(A, B)
  % Back Substitution Method
  % Solves AX=B
	% Inputs:
	%   - A is a NxN upper triangular matrix
  %   - B is a Nx1 matrix
	% Outputs:
	%   - X is the solution matrix
  n = length(B);
  X = zeros(n, 1);
  X(n) = B(n)/A(n, n);
  for k=n-1:-1:1
    div = A(k, k);
    if div != 0
      X(k) = (B(k) - A(k, k+1:n)*X(k+1:n))/A(k, k);
    else
      disp("Error: division by zero");
    endif
    k
  endfor
endfunction

<h3><strong>e) C&oacute;digo en Python</strong></h3>

In [11]:
import numpy as np


def gaussianElimination(A,B):
    n=len(A)
    A=np.array(A)
    B=np.array(B)
    X=(np.concatenate((A, B.T), axis=1)).astype(np.float)
    
    for i in range(0,n):
        pivot=X[i][i]
        pivotRow=X[i]
        M=np.zeros((1, n-i))
        m=M.size
        for k in range(1,m):
            M[k-1]=X[i+k][i] / pivot
        for k in range(1,m):
            X[i + k] = X[i + k] - pivotRow*M[k-1][k]
            
    X= backSubstitution(X[:,[0,n-1]],X[:,[n]])
    return X




def backSubstitution(A,B):
    n=len(B)
    X=np.zeros((n,1))
    X[n-1]=B[n-1]/A[n-1][n-1]
    for k in range(n-2,n-1):
        div=A[k][k]
        if (div!=0):
             X[k][k]=int(((B[k][k])-((A[k][k+1])*(X[k+1][k])))/(A[k][k]))
            
        else:
            print("Error division por cero")
    return X


<h3><strong>e) Ejemplo Num&eacute;rico</strong></h3>

Resuelva, utilizando artimetica punto 
otante con 3 cifras signicativas y
redondeo, el siguiente sistema lineal:

$\left\{\begin{matrix}
0.03x + &58.9y & = 59.2 \\ 
5.31x- &6.10y  & = 47
\end{matrix}\right.$

In [9]:
gaussianElimination([0.03 58.9 ; 5.31 -6.10], [59.2; 47])

k =  1
ans =

   10.0000
    1.0000



In [12]:
gaussianElimination([[0.03, 58.9] ,[ 5.31, -6.10]], [[59.2,47]])

array([[10.],
       [ 1.]])

<a id='biseccion'></a>
<h2><span style="color: #993300;"><span style="text-decoration: underline;"><strong>M&eacute;todo 2:</strong> Factorización LU</span></span></h2>

<h3><strong>a) Formulaci&oacute;n Matem&aacute;tica</strong></h3>


$Ax=b $

$A=LU $

$L \in \mathbb{R}^{nxn} , U \in \mathbb{R}^{nxn}$


<h3><strong>b) Valores Iniciales</strong></h3>

  <li>Matriz A de tamaño mxn</li>
  <li>Vector x de tamaño n</li>
  <li>Vector b de tamaño m</li>

<h3><strong>c) Ventajas y Desvantajas</strong></h3>

<div class="alert alert-block alert-success row">
    <div class="column">
        <p>
            <span style="text-decoration: underline;">
                <span style="text-decoration: underline;">
                    <strong>Ventajas:</strong>
                </span>
            </span>
        </p>
        <li>Siempre converge</li>
        <li>Útil como aproximación inicial de otros métodos</li>
    </div>
    <div class ="column">
        <p>
            <span style="text-decoration: underline;">
                <span style="text-decoration: underline;">
                    <strong>Desventajas:</strong>
                </span>
            </span>
        </p>
        <li>Es complejo pues observe que para la obtencionn de la factorizacion LU se realiza la fase 1 del metodo de eliminacion gaussiana</li>
        <li>Debido a la inestabilidad de este método, deben tenerse en cuenta algunos casos especiales, por ejemplo, si uno o varios elemento de la diagonal principalde la matriz a factorizar es cero, es necesario premultiplicar la matriz por una o varias matrices elementales de permutación</li>
    </div>
</div>

<h3><strong>c) Pasos del m&eacute;todo (Pseudoc&oacute;digo)</strong></h3>

![](LU.PNG)

<h3><strong>d) C&oacute;digo en GNU Octave</strong></h3>

In [15]:
function [L, U, Xk] = lu(X,B)
  n = length(X);
  L = eye(n);
  U = X;
  % For each row of matrix X
  for i=1:n

    pivot = U(i, i);
    pivotRow = U(i, :);
    % Multipliers' vector
    M = zeros(1, n - i);
    m = length(M);
    % Get each row multiplier

    for k=1:m

      M(k) = U(i + k, i) / pivot;
    endfor
    % Modify each row and each L subcolumn
    for k=1:m
      U(i + k, :) = U(i + k, :) - pivotRow*M(k);
      L(i + k, i) = M(k);
    endfor
  endfor
  Y=inv(L)*B;
  Xk=inv(U)*Y;  
endfunction


<h3><strong>d) C&oacute;digo en Python</strong></h3>

In [18]:
import numpy as np


def lu(X,B):
    n=len(X)
    L=np.eye(n)
    U=X
    
    for i in range(1,n):

        pivot =U[i-1][i-1]
        pivotRow=U[i-1]
        M=np.zeros((1, n-i))
        m=M.size+1
        for k in range(1,m):
            try:
                M[i-1][k-1]=(U[i + k -1][i-1] )/pivot
            except:
                M=(U[i + k -1][i-1] )/pivot
        for k in range(1,m):
            try:
                U[i+k-1]=U[i+k-1] - (np.multiply(pivotRow,M[i-1][k-1]))
                L[i+k-1][i-1]=M[i-1][k-1]
            except:
                U[i+k-1]=U[i+k-1] - (np.multiply(pivotRow,M))
                L[i+k-1][i-1]=M
                
    Y=((np.linalg.inv(L)).dot(np.transpose(B)))
    Xk=(np.linalg.inv(U)).dot( Y)

    return Xk

<h3><strong>e) Ejemplo Num&eacute;rico</strong></h3>

Resuelva el siguiente sistema 

$\begin{matrix}
4x_{1}- & 2x_{2} &+x_{3}  & =11\\ 
20x_{1}- & 7x_{2} &+ 12x_{3} & =70\\ 
-8x_{1} +& 13x_{2} & +17x_{3} & =17
\end{matrix}$

In [16]:
[L,U,Xk]=lu([4 -2 1; 20 -7 12 ; -8 13 17],[11; 70; 17])

L =

   1   0   0
   5   1   0
  -2   3   1

U =

   4  -2   1
   0   3   7
   0   0  -2

Xk =

   1.0000
  -2.0000
   3.0000



In [19]:
lu([[4, -2, 1],[20, -7, 12],[ -8, 13, 17]],[11, 70, 17])

array([ 1., -2.,  3.])

<a id='biseccion'></a>
<h2><span style="color: #993300;"><span style="text-decoration: underline;"><strong>M&eacute;todo 3:</strong> Factorización de Cholesky</span></span></h2>

<h3><strong>a) Formulaci&oacute;n Matem&aacute;tica</strong></h3>


$Ax=b$

$LL^{T}x=b$

$L \in \mathbb{R}^{nxn}$


<h3><strong>b) Valores Iniciales</strong></h3>

  <li>Matriz A de tamaño mxn simétrica positiva definida</li>
  <li>Vector x de tamaño n</li>
  <li>Vector b de tamaño m</li>

<h3><strong>c) Ventajas y Desvantajas</strong></h3>

<div class="alert alert-block alert-success row">
    <div class="column">
        <p>
            <span style="text-decoration: underline;">
                <span style="text-decoration: underline;">
                    <strong>Ventajas:</strong>
                </span>
            </span>
        </p>
        <li>Siempre converge</li>
        <li>Útil como aproximación inicial de otros métodos</li>
    </div>
    <div class ="column">
        <p>
            <span style="text-decoration: underline;">
                <span style="text-decoration: underline;">
                    <strong>Desventajas:</strong>
                </span>
            </span>
        </p>
        <li>Es complejo pues observe que para la obtencionn de la factorizacion LU se realiza la fase 1 del metodo de eliminacion gaussiana</li>
        <li>Alta complejidad Computacional</li>
    </div>
</div>

<h3><strong>c) Pasos del m&eacute;todo (Pseudoc&oacute;digo)</strong></h3>

![](Choleski.PNG)

<h3><strong>d) C&oacute;digo en GNU Octave</strong></h3>

In [21]:
function X = cholesky(A,b)
  n = length(A);
  L = zeros(n);
  for i=1:n
    for j=1:i
      if j==i
        sum = 0;
        for k=1:j-1
          sum = sum + L(j, k)^2;
        endfor
        L(j,j) = sqrt(A(j, j) - sum);
      else
        sum = 0;
        for k=1:j-1
          sum = sum + L(i, k)*L(j, k);
        endfor  
        L(i, j) = (1/L(j, j))*(A(i, j) - sum);
      endif
    endfor
  endfor

  X=inv(L*L')*b';
endfunction

<h3><strong>e) C&oacute;digo en Python</strong></h3>

In [25]:
import numpy as np
from math import sqrt
from pprint import pprint
 
def cholesky(A,B):
    """Performs a Cholesky decomposition of A, which must 
    be a symmetric and positive definite matrix. The function
    returns the lower variant triangular matrix, L."""
    n = len(A)

    # Create zero matrix for L
    L = [[0.0] * n for i in range(n)]

    # Perform the Cholesky decomposition
    for i in range(n):
        for k in range(i+1):
            tmp_sum = sum(L[i][j] * L[k][j] for j in range(k))
            
            if (i == k): # Diagonal elements
                # LaTeX: l_{kk} = \sqrt{ a_{kk} - \sum^{k-1}_{j=1} l^2_{kj}}
                L[i][k] = sqrt(A[i][i] - tmp_sum)
            else:
                # LaTeX: l_{ik} = \frac{1}{l_{kk}} \left( a_{ik} - \sum^{k-1}_{j=1} l_{ij} l_{kj} \right)
                L[i][k] = (1.0 / L[k][k] * (A[i][k] - tmp_sum))
    mul=L*np.transpose(L)
    X=np.linalg.inv(mul).dot( np.transpose(B))
    return X
 
#cholesky([[25, 15, -5, -10] ,[ 15, 10, 1, -7], [-5, 1, 21, 4], [-10, -7, 4, 18]],[-5, -4, -5, -2])

<h3><strong>f) Ejemplo Num&eacute;rico</strong></h3>

Considere la matriz

$A=\left ( \begin{matrix}
25 & 15 & -5 &-10 \\ 
15 &10  &1  & -7\\ 
 -5&  1&  21& 4\\ 
 -10&  -7&  4& 18
\end{matrix} \right )$

Si $b=(-25 -19 -21 -5)^{t}$ entonces resuelva el sistema de
ecuaciones lineales $Ax =b$

In [27]:
L=cholesky([25 15 -5 -10 ; 15 10 1 -7; -5 1 21 4; -10 -7 4 18],[-25 -19 -21 -5])

L =

  -1.00000
  -1.00000
  -1.00000
  -1.00000



In [28]:
cholesky([[25, 15, -5, -10] ,[ 15, 10, 1, -7], [-5, 1, 21, 4], [-10, -7, 4, 18]],[-25, -19, -21, -5])

array([ -1.  , -19.  ,  -5.25,  -1.25])